---
name: Test image build

on:
    pull_request:

jobs:
    build-image:
        name: Build image
        runs-on: ubuntu-latest
        steps:
            # Adding Docker Buildx cache
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # Adding docker hub login
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

              # Adding docker build test without pushing
            - name: Docker build
              uses: docker/build-push-action@v5
              with:
                push: false
                tags: nmofonseca/nettools:latest